mlynch/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', include(('portfolio.urls', 'portfolio'), namespace='portfolio')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from portfolio import views

urlpatterns = [
    path(r'', views.StatementList.as_view(), name='home'),
    path(r'certifications/', views.CertificationList.as_view(), name='certifications'),
    path('projects/', views.ProjectList.as_view(), name='projects'),
    path('projects/<slug:slug>/', views.ProjectDetail.as_view(), name='project_detail'),
] 

portfolio/models.py
from django.db import models
from django.contrib.auth.models import User

from utilities.models import BaseModel


class Statement(BaseModel):
    title = models.CharField(max_length=40)
    content = models.TextField()
    url_info = models.URLField(blank=True)
    
        
# class ImageLink(BaseModel):
#     image = models.ImageField(upload_to='main')
#     alttext = models.TextField()
        
class Project(BaseModel):
    STATUS = (
        (0, "Planning"),
        (1, "Development"),
        (2, "Maintaining"),
    )
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    content = models.TextField()    
    status = models.IntegerField(choices=STATUS)
    url = models.URLField()

    class Meta:
        ordering = ['-modified_date']
    
    def __str__(self):
        return self.title


class Certification(models.Model):
    LEVEL = (
        (0, "Beginner"),
        (1, "Intermediate"),
        (2, "Advanced"),
    )
    name = models.CharField(max_length=50, unique=True)
    badge = models.ImageField(blank=True, upload_to='certs')
    expiration_date = models.DateField(blank=True)
    url = models.URLField()
    level = models.IntegerField(choices=LEVEL)

    class Meta:
        ordering = ['-level']
    
    def expires(self):
        """
        Whether the certification expires or not.
        """
        if self.expiration_date:
            return True
        return False
    
    def __str__(self):
        return self.name

utilities/models.py
from django.db import models

class BaseModel(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

portfolio/views.py
from typing import List, Union

from django.views import generic

from .models import Statement
from .models import Project
from .models import Certification



class StatementList (generic.ListView):    
    # queryset_imagelinks = ImageLink.objects.all()
    # queryset = blend(queryset_statements, queryset_imagelinks)
    queryset = Statement.objects.all()
    template_name = 'statements.html'    

class ProjectList(generic.ListView):
    queryset = Project.objects.filter(status__gte=1)
    template_name = 'projects.html'

class ProjectDetail(generic.DetailView):
    model = Project
    template_name = 'project_detail.html'

class CertificationList(generic.ListView):
    #breakpoint()
    queryset = Certification.objects.all()
    template_name = 'certifications.html'

portfolio/templates/index.html
<!DOCTYPE html>
<html lang ="en">

  <head>
    <title>Michael K. Lynch</title>
  </head>
<body>

  <div id="navigation">
    <div class="table">
      <ul id="horizontal-list">

	
	<li><a href="/professional">Professional</a></li>
	
	<li><a href="/certifications">Certifications</a></li>
	
	<li><a href="/projects">Projects</a></li>
	
	<li><a href="/contact">Contact</a></li>
	

      </ul>
    </div>
  </div>

  <h1>Michael K. Lynch</h1>
  <p>Page under construction</p>
  
</body>
	<!---WorkEducatione eg certs Projects Contact --->
</html>

templates/base.grid.html
{% load static %} 
<!DOCTYPE html>
<html lang ="en">
    <head>
	<title>Michael K. Lynch</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<!-- <link rel="stylesheet" href="{%  static 'aesthetic.css' %}"> -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no"> 
    </head>    


    <section id="page">
	<header> Navbar </header>
	<main> <!-- Content -->
	    {% block content %}	   

	    {% endblock content %}	
	</main>
	<footer>Footer</footer>
</div>
    </section>
</html>

templates/base.html
{% load static %} 
<!DOCTYPE html>
<html lang ="en">
    <head>
      <title>Michael K. Lynch</title>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    </head>    

    <style>
body {
  padding-top: 60px;
}
@media (max-width: 979px) {
  body {
    padding-top: 0px;
  }
}
</style>
    <body class="d-flex flex-column h-100 bg-white">
    
	<header>
	    <!-- Fixed navbar -->
	    <nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
		<a class="navbar-brand" href="#">mlyn.ch</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarCollapse">
		    <ul class="navbar-nav mr-auto">
			<li class="nav-item active">
			    <a class="nav-link" href="{% url 'portfolio:home' %}">About <span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item">
			    <a class="nav-link" href="{% url 'portfolio:projects' %}">Portfolio</a>
			</li>
			<li class="nav-item">
			    <a class="nav-link" href="{% url 'portfolio:certifications' %}">Certifications</a>
			</li>
		    </ul>
		</div>
	    </nav>
	</header>
	
	<!-- Begin page content -->
	<main role="main" class="flex-shrink-0 bg-white">
	    <div class="container">
		<!-- Content -->
		{% block content %}
		
		{% endblock content %}	
	    </div>
	</main>
	
	<footer class="footer mt-auto py-3 fixed-bottom">
	    <div class="<!-- comment -->ntainer">
    <span class="text-muted">2021</span>
	    </div>
	</footer>		
    </body>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    -->
	
</html>

templates/index.bootstrap.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Michael K. Lynch</h1>
    <p class="lead">Page under construction.</p>
  </div>
</div>
<p>Pre statement</p>
{% for statement in statements %}
<p>In statement loop</p>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <p class="card-text">{{ statement.content }}</p>
  </div>
</div>
{% endfor %}
<p>Post statement</p>
{% endblock %}

templates/index.html
{% extends "base.bootstrap.html" %}
{% block content %}
<div class="nameplate">	  
  <h1>Michael K. Lynch</h1>
  <h2>Page under constructionss</h2>
</div>
{% endblock %}

templates/portfolio/certifications.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="row">
    {% for cert in certification_list %}
    <div class="card" style="width: 18rem;">
      <img src="{{ cert.badge.url }}" class="card-img-top" alt="Certification Icon">
      <div class="card-body">
	<h5 class="card-title">{{ cert.name }}</h5>
	<a href="{{ cert.url }}" target="_blank" class="btn btn-primary">Validate</a>
      </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/portfolio/home.bootstrap.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Michael K. Lynch</h1>
    <p class="lead">Page under construction.</p>
  </div>
</div>
{% endblock %}

templates/portfolio/home.html
{% extends "base.html" %}
{% block content %}
<div class="nameplate">	  
  <h1>Michael K. Lynch</h1>
  <h2>Page under construction</h2>
</div>
{% endblock %}

templates/portfolio/project_detail.html
{% extends 'base.html' %}
{% block content %}
<div>
  <h2>
    <br>
    <br>
    <br>
    Project details coming soon!
    <br>
    <br>
    <br>
</h2>
</div>
{% endblock content %}

templates/portfolio/projects.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <!-- Project Entries Column -->	
    {% for project in project_list %}
    <div class="card" style="width: 18rem;">
      <!-- <img src="" alt="" /> src="..." class="card-img-top" alt="..."> -->
      <div class="card-body">
	<h5 class="card-title">{{ project.title }}</h5>
	<p class="card-text">{{project.content|slice:":200" }}</p>
	<a href="{% url 'portfolio:project_detail' project.slug  %}" class="btn btn-primary">Read More</a>
      </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/portfolio/statements.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Michael K. Lynch</h1>
    <p class="lead">Page under construction.</p>
  </div>
      </div>

  <div class="container">
    <div class="row">
        <!-- Statement Entries Column -->	
	{% for statement in statement_list %}
	<div class="card" style="width: 36rem;">
	  <div class="card-body">
	    <p class="card-text">{{ statement.content }}</p>
	  </div>
	</div>
	{% endfor %}	
</div>
{% endblock %}
    